// Code Generated by Sidekick is for learning and experimentation purposes only.
import { useEffect } from "react";
import { supabaseClient } from "@/lib/supabase/client";
import { useVaultStore } from "@/store/useVaultStore";

// Store expects these statuses only
type AllowedStatus = "Pending" | "Error" | "OK" | "Suspect" | "Missing";

// Supabase might return other statuses, so use a wider type
interface DocRow {
  id: string;
  status: string; // Accept anything, but we'll validate below
}

// Runtime validation function
function isAllowedStatus(status: string): status is AllowedStatus {
  return (
    status === "Pending" ||
    status === "Error" ||
    status === "OK" ||
    status === "Suspect" ||
    status === "Missing"
  );
}

export function useDocPolling() {
  const docs = useVaultStore(s => s.docs);
  const setStatus = useVaultStore(s => s.setStatusByRemoteId);

  useEffect(() => {
    const ids = docs.map(d => d.remoteId).filter(Boolean) as string[];
    if (ids.length === 0) return;

    const t = setInterval(async () => {
      const { data } = await supabaseClient
        .from("documents")
        .select("id,status")
        .in("id", ids);

      (data as DocRow[] | null)?.forEach(row => {
        if (isAllowedStatus(row.status)) {
          setStatus(row.id, row.status); // Only allowed status values pass
        } else {
          // Optionally: Log or handle unknown statuses here
          // For example: setStatus(row.id, "Error");
        }
      });
    }, 2500);

    return () => clearInterval(t);
  }, [docs, setStatus]);
}