// Code Generated by Sidekick is for learning and experimentation purposes only.
import { useEffect } from "react";
import { supabaseClient } from "@/lib/supabase/client";
import { useVaultStore } from "@/store/useVaultStore";
import { dbToUiStatus, type DbDocStatus, type UiDocStatus } from "@/types";

// Supabase returns DB statuses (lowercase)
interface DocRow {
  id: string;
  status: string; // DB returns lowercase: "pending", "ok", "suspect", "missing"
}

// Runtime validation function to check if status is a valid DB status
function isDbStatus(status: string): status is DbDocStatus {
  return (
    status === "pending" ||
    status === "ok" ||
    status === "suspect" ||
    status === "missing"
  );
}

export function useDocPolling() {
  const docs = useVaultStore(s => s.docs);
  const setStatus = useVaultStore(s => s.setStatusByRemoteId);

  useEffect(() => {
    const ids = docs.map(d => d.remoteId).filter(Boolean) as string[];
    if (ids.length === 0) return;

    const t = setInterval(async () => {
      const { data } = await supabaseClient
        .from("documents")
        .select("id,status")
        .in("id", ids);

      (data as DocRow[] | null)?.forEach(row => {
        if (isDbStatus(row.status)) {
          // Convert DB status (lowercase) to UI status (uppercase)
          const uiStatus: UiDocStatus = dbToUiStatus(row.status);
          setStatus(row.id, uiStatus);
        }
        // Unknown statuses are ignored
      });
    }, 2500);

    return () => clearInterval(t);
  }, [docs, setStatus]);
}